/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sun.glb --types 
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { SUN } from "@/lib/simulation/data";

type ActionName = "Take 001";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    UnstableStarCore_1_0: THREE.Mesh;
    UnstableStarref_2_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    material_1: THREE.MeshPhysicalMaterial;
  };
  animations: GLTFAction[];
};

type SunModelProps = JSX.IntrinsicElements["group"] & {
  registerTarget: (name: string, obj: THREE.Object3D) => void;
  onSelect: (name: string, obj: THREE.Object3D) => void;
};

export function SunModel({
  registerTarget,
  onSelect,
  ...props
}: SunModelProps) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/sun.glb",
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group
      // ref={group}
      ref={(obj) => {
        if (obj) {
          group.current = obj;
          registerTarget(SUN.name, obj);
        }
      }}
      {...props}
      dispose={null}
      onClick={(e) => {
        e.stopPropagation();
        if (group.current) onSelect(SUN.name, group.current);
      }}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3a2aaa22fb3d4b329318a980ad1bf6d1fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="UnstableStarCore_1_0"
                    geometry={nodes.UnstableStarCore_1_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="UnstableStarref"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1.01}
                >
                  <mesh
                    name="UnstableStarref_2_0"
                    geometry={nodes.UnstableStarref_2_0.geometry}
                    material={materials.material_1}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/sun.glb");
